### PR TITLE
[MRG] CI test python 2.x and 3.x

### PR DESCRIPTION
**Pull request by glemaitre**
Allows to test both 2.x and 3.x python version

### CODE REVIEW

**Comment by glemaitre** [comment]
@agramfort @kegl This should make the job

**Comment by agramfort** [comment]
green !

thx @glemaitre 

can you do the same for the other ramps-kits? boston and titanic?

**Comment by glemaitre** [comment]
Done for others

**Comment by glemaitre** [comment]
And something to keep in mind (at least I didn't know), IPython 6.x+ are not going to support python 2 anymore. It will be stalled to IPython 5.x LTS: https://ipython.readthedocs.io/en/stable/

It might have some impact with the jupyter-notebook development ...

**Pull request merged**
